### ISSUE TITLE
Missing working example

### ISSUE THREAD

**Issue by henno** [maksekeskus/maksekeskus-php#1]
Tere!

The API doc, while useful for understanding the protocol, does not really answer how this class is supposed to be used.

After hacking for 4 hours, I managed to successfully authenticate against Maksekeskus server and create a transaction:

```
$maksekeskus = new \Maksekeskus\Maksekeskus($shopId, $publishableKey, $secretKey, $testEnv);
$maksekeskus->createTransaction(['transaction' => [
    'amount' => 12.95,
    'currency' => 'EUR',
    'reference' => 1,
    'merchant_data' => '234567890;abc113;new_transaction=5432'
], 'customer' => [
    "email" => "customer@laalaa.com",
    "ip" => "84.50.108.210",
    "country" => "ee",
    "locale" => "en"
]]);
```

It is unclear, though, what would be the next step.

And what is the role of merchant_data and how will the customer IP be processed?

**Comment by ragulka** [comment]
I second, working examples are really missing from the whole documentation.

**Comment by zorroh** [comment]
+1

**Comment by priitpiile** [comment]
We have,

a) created more easily distributable package, available under the repository releases
https://github.com/maksekeskus/maksekeskus-php/releases
and added short example to start with.

b)
made publicly available an "api explorer" that aims to demonstrate the API usage further in 'hand-on' mode. 
See: https://maksekeskus.ee/api-explorer/intro.php

we'll continue improving it incrementally, your suggestions welcomed...
